const DATABASEURL = process.env.DATABASE_URL;
const PORT = process.env.PORT;

const NODE_ENV = process.env.NODE_ENV;

const ACCESS_TOKEN_SECRET_KEY = process.env.ACCESS_TOKEN_SECRET_KEY;
const REFRESH_TOKEN_SECRET_KEY = process.env.REFRESH_TOKEN_SECRET_KEY;
const RESET_PASSWORD_SECRET_KEY = process.env.RESET_PASSWORD_SECRET_KEY;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;

const FRONTEND_URL = process.env.FRONTEND_URL;

const EMAIL_USERNAME = process.env.EMAIL_USERNAME;
const EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;

const BACKEND_SERVER_URL = process.env.BACKEND_SERVER_URL;

export {
  DATABASEURL,
  PORT,
  NODE_ENV,
  ACCESS_TOKEN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY,
  RESET_PASSWORD_SECRET_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  FRONTEND_URL,
  EMAIL_USERNAME,
  EMAIL_PASSWORD,
  BACKEND_SERVER_URL
};
